### ISSUE TITLE
Vue validation not working properly for required fields

### ISSUE THREAD

**Issue by shadowam** [eolant/laravel-vuetify-spa-starter#1]
Hello!

I've been using your starter package to build a system and I can't find how to fix the 'required' validation made in /mixins/forms.

Everytime I use it, i get 'undefined' as field name, even without altering anything from your package.

You can try it after logging in and trying to edit your profile: Leave name or password field blank and the validation will occur with 'undefined' field.

![image](https://user-images.githubusercontent.com/6698296/50522273-34a18300-0ab1-11e9-9619-6baa3d5d23ea.png)

Could you please help me?

**Comment by eolant** [comment]
Hi!
Thanks for spotting this. Indeed something might of changed from the older versions or I messed up and didn't notice it before but it's fixed now :)
