### ISSUE TITLE
'laravel-vuetify-spa-starter' not working on IE or Edge

### ISSUE THREAD

**Issue by spatialhast** [eolant/laravel-vuetify-spa-starter#6]
'laravel-vuetify-spa-starter' not working on IE or Edge
Errors:
- IE 11: "SCRIPT1003: Expected ':'"
- Edge: "SCRIPT1028: SCRIPT1028: Expected identifier, string or number"
I configured 'vue.config.js', '.babelrc', babel.config.js' according to https://vuetifyjs.com/en/getting-started/quick-start#edge-support but no success.
How to configure webpack?

**Comment by eolant** [comment]
@spatialhast I'm in the process of updating this repo and going to try [this](https://github.com/JeffreyWay/laravel-mix/issues/971#issuecomment-322300417)

**Comment by eolant** [comment]
@spatialhast Can you please close the issue if this code resolved it?
