### ISSUE TITLE
Access to XMLHttpRequest at 'http://localhost/api/register' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by ahmedTareque** [eolant/laravel-vuetify-spa-starter#9]
![image](https://user-images.githubusercontent.com/16764227/68591179-4c5fdb00-04ba-11ea-94fa-45b659d8e551.png)

Can anyone has any idea why it's not working?

**Comment by eolant** [comment]
Domains must match for your API requests or you should enable CORS on Laravel.
